name: ConodiaSanction
version: '1.0-SNAPSHOT'
main: fr.blixow.conodia.ConodiaSanction
api-version: 1.8
authors: [ blixow14, SYNATIKS ]
description: plugin de sanction de conodia
commands:
  mute:
    description: commande de mute
  unmute:
    description: commande d'unmute
    aliases: demute
  ban:
    description: commande de ban
    aliases: tempban
  unban:
    description: commande d'unban
    aliases: deban
  kick:
    description: commande de kick
